minetest.register_node(":default:lava_source", {
	description = "Lava Source",
	inventory_image = minetest.inventorycube("default_lava.png"),
	drawtype = "liquid",
	tiles = {
		{
			name = "lavatile.png",
			normal_texture = "lavatile_normal.png",
			special_texture = "lavatile_noise.png",
			force_bilinear_filtering = true,
		},
	},
	special_tiles = {
		{
			name = "lavatile.png",
			normal_texture = "lavatile_normal.png",
			special_texture = "lavatile_noise.png",
			force_bilinear_filtering = true,
			backface_culling = false,
		},
	},
	shader = "lava_surface_shader",
	paramtype = "light",
	light_source = default.LIGHT_MAX - 1,
	walkable = false,
	pointable = false,
	diggable = false,
	buildable_to = true,
	is_ground_content = false,
	drop = "",
	drowning = 1,
	liquidtype = "source",
	liquid_alternative_flowing = "default:lava_flowing",
	liquid_alternative_source = "default:lava_source",
	liquid_viscosity = 7,
	liquid_renewable = false,
	damage_per_second = 4 * 2,
	post_effect_color = {a = 192, r = 255, g = 64, b = 0},
	groups = {lava = 3, liquid = 2, hot = 3, igniter = 1},
})

minetest.register_node(":default:lava_flowing", {
	description = "Flowing Lava",
	inventory_image = minetest.inventorycube("default_lava.png"),
	drawtype = "flowingliquid",
	special_tiles = {
		{
			name = "lavatile.png",
			normal_texture = "lavatile_normal.png",
			special_texture = "lavatile_noise.png",
			force_bilinear_filtering = true,
			backface_culling = false,
		},
		{
			name = "lavatile.png",
			normal_texture = "lavatile_normal.png",
			special_texture = "lavatile_noise.png",
			force_bilinear_filtering = true,
			backface_culling = true,
		},
		
	},
	shader = "lava_surface_shader",
	paramtype = "light",
	paramtype2 = "flowingliquid",
	light_source = default.LIGHT_MAX - 1,
	walkable = false,
	pointable = false,
	diggable = false,
	buildable_to = true,
	is_ground_content = false,
	drop = "",
	drowning = 1,
	liquidtype = "flowing",
	liquid_alternative_flowing = "default:lava_flowing",
	liquid_alternative_source = "default:lava_source",
	liquid_viscosity = 7,
	liquid_renewable = false,
	damage_per_second = 4 * 2,
	post_effect_color = {a = 192, r = 255, g = 64, b = 0},
	groups = {lava = 3, liquid = 2, hot = 3, igniter = 1,
		not_in_creative_inventory = 1},
})
